### ISSUE TITLE
loading the event broadcaster crashes OEP

### ISSUE THREAD

**Issue by pplenck** [open-ephys-plugins/event-broadcaster#1]
Hello
I am trying to use the event broadcaster but it crashes open ephys when I drag and drop it to the signal chain.
I installed it using the file->PluginInstaller option. 
I had an isue with a missing dll, so I copied it from outside with a bunch of others that gave me trouble last time:
msvcp120, msvcp100 msvcr etc...
then I had another issue: the plugin was not available but seen by the installer as already installed...
so i went to another folder that actually had some dlls here: ProgramData/open ephys/plugins and deleted everything
re ran an install.
now I see the blugin but it can't load
 what did I miss?
thanks for your input

**Comment by pplenck** [comment]
note: I use windows 
I uninstalled everything and reinstalled OpenEphys on a single folder. Reinsalled the plugin, still crashes when I try to load the plugin in the signal chain. Should I compile it myself?

**Comment by anjaldoshi** [comment]
Hey, can you install the [VS2013 runtime](https://www.microsoft.com/en-us/download/details.aspx?id=40784) and see if that resolves your issue?

**Comment by pplenck** [comment]
no, 
I tried reinstalling eveything again after I installed the runtime and did not need to add the dlls when installing the plugin.
however, it crashed immediately when I added the plugin in the signal chain.
Is there a way to accesss an error report somewhere?

**Comment by anjaldoshi** [comment]
Currently, there isn't a way to access an error report. We are working on such a feature to generate error reports, if any, during every run of the GUI. 

Can you answer some of my questions so that I can help you debug this issue better?
- What version of the GUI are you running?
- Does this issue occur when you install ZMQInterface or NetworkEvents plugins?

**Comment by pplenck** [comment]
HI
I am using the latest version of the GUI (as of today) 
I am able to load both zmqinterface and NetworkEvents plugins. I am also able to drag and drop them in the signal chain without any problem.
I haven't tried if they work properly though 
thx!

**Comment by anjaldoshi** [comment]
Looks like we forgot to update Event Broadcaster to make it work with GUI version v0.5.3 and above. I'll do that and a new version should be available within the next hour which should fix this crashing issue. I'll let you know when it is ready.

**Comment by pplenck** [comment]
Cool, thanks!

**Comment by anjaldoshi** [comment]
New version (v0.1.1) of Event Broadcaster is up. You can upgrade to the latest version via Plugin Installer (restarting the GUI after upgrading is recommended). Let me know if this fixes the issue on your end.

**Comment by pplenck** [comment]
It works Now!
Would you kindly show us a script (matlab if possible but python might do) that reads these events?
thanks a lot
